export const mockEvents = [
  {
    id: "1",
    name: "春季ビーチボールバレー大会",
    event_date: "2025年8月20日",
    start_time: "09:00",
    venue: "大宮市民体育館",
    prefecture: "埼玉県",
    participants: 15,
    maxParticipants: 32,
    entryFee: 3000,
    type: "tournament" as const,
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=600&fit=crop",
    description: "年に一度の春季大会です。初心者から上級者まで幅広く参加いただけます。",
    beginnerFriendly: true,
    status: "recruiting" as const,
    rules: "ラリーポイント制",
    prizes: {
      first: "商品券 30,000円",
      second: "商品券 20,000円",
      third: "商品券 10,000円"
    },
    createdAt: new Date().toISOString() // Today
  },
  {
    id: "2",
    name: "水曜夜練習会",
    event_date: "2025年7月30日",
    start_time: "19:00",
    venue: "川越第二体育館",
    prefecture: "埼玉県",
    participants: 12,
    maxParticipants: 20,
    entryFee: 500,
    type: "practice" as const,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop",
    description: "毎週水曜日の定期練習会です。基礎練習からゲーム形式まで行います。",
    beginnerFriendly: true,
    status: "recruiting" as const,
    skillLevel: "all",
    createdAt: new Date(Date.now() - 86400000).toISOString() // Yesterday
  },
  {
    id: "3",
    name: "全国大会",
    event_date: "2025年11月20日",
    start_time: "大会要項をご確認ください",
    venue: "東京体育館",
    prefecture: "東京都",
    participants: 48,
    maxParticipants: 64,
    entryFee: 5000,
    type: "tournament" as const,
    image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&h=600&fit=crop",
    description: "全国から強豪チームが集まる大会です。",
    beginnerFriendly: false,
    status: "recruiting" as const,
    rules: "ラリーポイント制",
    prizes: {
      first: "賞金 100,000円",
      second: "賞金 50,000円",
      third: "賞金 30,000円"
    },
    createdAt: new Date().toISOString() // Today
  },
  {
    id: "4",
    name: "初心者向け練習会",
    event_date: "2025年8月5日",
    start_time: "10:00",
    venue: "さいたま市民体育館",
    prefecture: "埼玉県",
    participants: 8,
    maxParticipants: 16,
    entryFee: 300,
    type: "practice" as const,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    description: "初心者向けの練習会です。基本的な動作から丁寧に指導します。",
    beginnerFriendly: true,
    status: "recruiting" as const,
    skillLevel: "beginner",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString() // 2 days ago
  },
  {
    id: "5",
    name: "エリア選手権大会",
    event_date: "2025年9月15日",
    start_time: "09:00",
    venue: "川口市体育館",
    prefecture: "埼玉県",
    participants: 20,
    maxParticipants: 24,
    entryFee: 2500,
    type: "tournament" as const,
    image: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&h=600&fit=crop",
    description: "埼玉エリアの選手権大会です。",
    beginnerFriendly: false,
    status: "recruiting" as const,
    rules: "ラリーポイント制",
    prizes: {
      first: "トロフィー + 商品券 20,000円",
      second: "商品券 10,000円",
      third: "商品券 5,000円"
    },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString() // 3 days ago
  },
  {
    id: "6",
    name: "週末練習会",
    event_date: "2025年8月10日",
    start_time: "13:00",
    venue: "熊谷スポーツセンター",
    prefecture: "埼玉県",
    participants: 10,
    maxParticipants: 20,
    entryFee: 500,
    type: "practice" as const,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop",
    description: "週末の定期練習会です。中級者以上を対象としています。",
    beginnerFriendly: false,
    status: "recruiting" as const,
    skillLevel: "intermediate",
    createdAt: new Date().toISOString() // Today
  },
  {
    id: "7",
    name: "夏季チャンピオンシップ",
    event_date: "2025年8月25日",
    start_time: "08:30",
    venue: "横浜スポーツセンター",
    prefecture: "神奈川県",
    participants: 28,
    maxParticipants: 32,
    entryFee: 4000,
    type: "tournament" as const,
    image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=800&h=600&fit=crop",
    description: "夏の大型大会です。暑さ対策をしっかりして参加してください。",
    beginnerFriendly: true,
    status: "recruiting" as const,
    rules: "サイドアウト制",
    prizes: {
      first: "賞金 50,000円",
      second: "賞金 30,000円",
      third: "賞金 15,000円"
    },
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString() // 5 days ago
  },
  {
    id: "8",
    name: "上級者向け練習会",
    event_date: "2025年8月12日",
    start_time: "18:00",
    venue: "千葉県総合スポーツセンター",
    prefecture: "千葉県",
    participants: 14,
    maxParticipants: 16,
    entryFee: 700,
    type: "practice" as const,
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop",
    description: "上級者向けの練習会です。高度な戦術練習を行います。",
    beginnerFriendly: false,
    status: "recruiting" as const,
    skillLevel: "advanced",
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString() // 7 days ago
  }
]